### ISSUE TITLE
Comments at the end of the line

### ISSUE THREAD

**Issue by mmodenesi** [davidstutz/jquery-pseudocode#1]
Great Job! I'm using your code in a domestic project I use to organize my studies.
I realized that comments must be in a line of their own to avoid issues with other keywords:

This:

`while i $\lt$ n:  // hello, I'm a smart comment but I don't have my own line`

prevents `while`from being properly colored.

I realized it's because of 

``` javascript
if (commentLine === false) {
    // scan for keywords
}
```

on jquery-pseudocode.js

Is this just a small optimization or is it really troublesome to keep analyzing the line?

Thanks!

**Comment by davidstutz** [comment]
No its not troublesome, so you can change it if you like. I remember doing it this way because I mostly use  single-line comments and did not want words like "if", "for", "while" etc. highlighted in the comments.
